### ISSUE TITLE
Add details about uploading brink package in readme

### ISSUE THREAD

**Issue by hcs0** [chevah/brink#105]
Updating readme - can this be merged directory to master?

Text:

**Uploading the brink package**

Follow the instructions in the wiki under ``Development/Python`` to upload the new brink version.

**Comment by adiroiban** [comment]
I don't know what to say. Publishing brink / compat / keycert or any other python package should be common knowledge.

We have a private python repo... and the steps to do it are the same for all packages.

I don't think that we need to replicate this

**Comment by hcs0** [comment]
Yeah but the details are inconsistent.

For example, the README in this repo talks about creating a ticket, branch etc which is common knowledge.

But if someone is reading this and they have not published brink / compat etc for the first time then the info would be useful.

Having inconsistent / incomplete info across various repos is a crappy experience for anyone wanting to contribute to this.

**Comment by adiroiban** [comment]
Agree. I tried to update the readme as part of https://github.com/chevah/brink/pull/107 so you can try to push an updated README on that PR.

Thanks!
